name: AutoRefill
main: com.gmail.mmonkey.AutoRefill.AutoRefill
version: 1.0
commands:
   refill:
      description: Automatically refill the block in-hand, with the same block from your inventory, when you run out.
      usage: /refill [on/off], /refill [player] [on/off]
permissions:
   autorefill.*:
      description: Gives access to all AutoRefill commands / functions
      children:
         refill.use: true
         refill.on: true
         refill.off: true
         refill.player.on: true
         refill.player.off: true
      default: op
   autorefill.use:
      description: Allows player to use AutoRefill
      default: true
   autorefill.on:
      description: Allows player to turn AutoRefill on
      default: op
   autorefill.off:
      description: Allows player to turn AutoRefill off
      default: op
   autorefill.player.on:
      description: Allows player to turn on AutoRefill for a specified player
      default: op
   autorefill.player.off:
      description: Allows player to turn off AutoRefill for a specified player
      default: op